road-core/service

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/bam.py
ols/src/llms/providers/fake_provider.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
ols/src/llms/providers/watsonx.py
scripts/evaluation/utils/models.py

Fixed docstyle

---

.github/workflows/pydocstyle.yaml
Makefile
pdm.lock
pyproject.toml

Pydocstyle as devel dependency

Pydocstyle as devel dependency

---

ols/src/llms/providers/azure_openai.py
tests/integration/test_project_version_consistency.py

Integration test to ensuse project versions consistency

Integration test to ensuse project versions consistency

---

Containerfile

chore(deps): update quay.io/openshift-lightspeed/lightspeed-rag-content docker digest to a91aca8

chore(deps): update quay.io/openshift-lightspeed/lightspeed-rag-content docker digest to a91aca8

---

runner.py

Simplified the condition to start uvicorn. The TLS flags will be None in case they are not being used, so there is no need for branching that. The condition was moved to determinate the port of the running service.
- Closes #

Refactor start_uvicorn to be less verbose with conditionals

---

README.md
docs/config.puml
examples/olsconfig-local-ollama.yaml
examples/olsconfig.yaml
examples/openshift-lightspeed-tls.yaml
ols/app/models/config.py
runner.py
tests/benchmarks/test_config_loader.py
tests/config/valid_config.yaml
tests/unit/utils/test_config.py

This patch introduces the ability to increase the number of workers for the REST API via its configuration file.
- Closes #51

Add number of workers to scale up REST API

---

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
ols/src/prompts/prompts.py
scripts/build-container.sh
tests/config/operator_install/imagedigestmirrorset.yaml
tests/unit/llms/providers/test_azure_openai.py
tests/unit/llms/providers/test_openai.py
tests/unit/llms/providers/test_rhelai_vllm.py
tests/unit/llms/providers/test_rhoai_vllm.py

Sync with downstream 

---

pdm.lock
pyproject.toml

New dependency: pytest-subtests to be used in unit and integration tests

New dependency: pytest-subtests to be used in unit and integration tests

---

pdm.lock
pyproject.toml

OLS-1174: bump-up OpenAI to version 1.53.3

OLS-1174: bump-up OpenAI to version 1.53.3

---

tests/e2e/test_api.py

Removing test get cluster id function as it's not relevant as its not expected for k8s and cluster utils to have the same cluster id

Removing test get cluster id function as it's not relevant as its not expected for k8s and cluster utils to have the same cluster id

---

examples/rcsconfig.yaml
ols/app/main.py
ols/app/models/config.py
ols/src/auth/k8s.py
tests/integration/test_authorized.py
tests/integration/test_metrics.py
tests/unit/app/models/test_config.py

Provide options to Prometheus metrics and auth checks warnings in log. They are:
- `suppress_metrics_in_log` When this option is set to `true`, the output from `/metrics` are not sent to the log even if `app_log_level` is set to `debug`. Default is `false`.
- `suppress_auth_checks_warning_in_log` When this option is set to `true`, the `Auth checks disabled, skipping` warning message is suppressed on the log. Default is `false`
- Closes # n/a
Unit and integration test cases are provided.
Run the service and check the log output with setting each option to `true`.

Options to suppress Prometheus metrics and auth checks warnings in log

---

pdm.lock
pyproject.toml

OLS-1235: CVE fix in aiohttp

---

examples/rcsconfig.yaml
ols/app/endpoints/health.py
ols/app/models/config.py
tests/unit/app/endpoints/test_health.py

Add a new option `expire_llm_is_ready_persistent_state` to specify the expiration time to let the "LLM Ready" status, which is used in the response of `/readiness` API, in seconds. The default is `-1` (= never expires). If the expiration occurs, the next `/readiness` API call will make a call against LLM again to check the status of LLM.
- Related Issue # [AAP-35769](https://issues.redhat.com/browse/AAP-35769)
- Closes # [AAP-35769](https://issues.redhat.com/browse/AAP-35769)
Two new unit test cases are included in this PR.
Set `expire_llm_is_ready_persistent_state` to a small value, like `10` secs, call …

Option to let the LLM ready status get expired

---

pdm.lock
pyproject.toml

Bump-up Gradio to version 4.44.1 to avoid warning messages on startup

Bump-up Gradio to version 4.44.1 to avoid warning messages on startup

---

ols/app/endpoints/ols.py
ols/app/models/models.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/models/test_models.py

Ability to create ref docs from rag chunks

Ability to create ref docs from rag chunks

---

ols/constants.py
ols/user_data_collection/data_collector.py
runner.py
scripts/generate_openapi_schema.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_openapi.py

OLS-1308: environment variable with config file on one place

OLS-1308: environment variable with config file on one place

---

ols/utils/pyroscope.py
pyproject.toml
tests/unit/utils/test_pyroscope.py

Enable flake8 logger linter on CI

Enable flake8 logger linter on CI

---

docs/openapi.json
examples/rcsconfig.yaml
ols/app/endpoints/ols.py
ols/app/models/config.py
ols/app/models/models.py
ols/src/query_helpers/docs_summarizer.py
ols/src/query_helpers/query_helper.py
ols/src/ui/gradio_ui.py
tests/integration/test_ols.py
tests/unit/app/models/test_config.py

This is the implementation of Issue #158:
- A new optional string parameter `system_prompt` is added to the `/v1/query` endpoint. 
- System prompt override occurs only when `dev_config.enable_system_prompt_override` is set to `true`. 
- Default is `false`.
- When `dev_config.enable_system_prompt_override` is set to `false` and `/v1/query` is invoked with `system_prompt`, the value specified in `system_prompt` is ignored.
- Gradio UI is updated for specifying `system_prompt` for debug UI.  See the video attached to #158.
- Closes # n/a

Allow system prompt override for dev

---

pdm.lock
pyproject.toml

Bump-up Mypy to 1.14.1

---

ols/customize/__init__.py
ols/customize/ols/reranker.py
ols/src/query_helpers/docs_summarizer.py
tests/unit/query_helpers/test_docs_summarizer.py

We (Ansible Lightspeed Chatbot) are adding supplemental documents that will include what are not explicitly found in the product documentation. When those documents appear in DB search results, we want place them at higher ranks over other documents. For that purpose, we would like to allow reranking of Vector DB search results before truncating them within the token limit.  
The "reranker" is defined in the "custom" directory so that each product can define its own reranker.  The efault implementation does nothing and returns the given search results as they are.
- Closes #

Allow reranking nodes retrieved from vector DB

---

pdm.lock
pyproject.toml

Bump-up `Jinja2` to 3.1.5 to fix vulnerability

Bump-up Jinja2 to 3.1.5 to fix vulnerability

---

pdm.lock
pyproject.toml

Bump-up tqdm to 4.67.1

---

tests/integration/test_authorized.py
tests/integration/test_feedback.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py
tests/integration/test_redis.py

Get rid of global variables in integration tests

Get rid of global variables in integration tests

---

pdm.lock
pyproject.toml

Bump-up `aiohttp` to version 3.11.10

Bump-up aiohttp to 3.11.10

---

examples/rcsconfig.yaml
ols/app/models/config.py
ols/runners/uvicorn.py
tests/unit/app/models/test_config.py
tests/unit/runners/test_uvicorn_runner.py

In a development environment, we want to change the port number of the service, which is hard-coded to `8080` with non-secure connection. This PR will add a new configurable option `uvicorn_port_number` to `dev_config` so that developers can modify the service port number without editing a source code. When `uvicorn_port_number` is not specified, the code will work as it does today.
- Closes # n/a
Unit test cases are provided with the PR.

Support non-default uvicorn port number for dev

---

pdm.lock
pyproject.toml

Bump-up `faiss-cpu` to version `1.9.0.post1`

Bump-up faiss-cpu to version 1.9.0.post1

---

ols/src/query_helpers/docs_summarizer.py

#228 had a bug. It introduced "Reranker", which was suppsed to be provided per project, but in `docs_summarizer.py`, the OLS-version of reranker was statically linked to the code.  This PR is for fixing that issue.
- Closes # n/a
Issue a regular `/query` call to make sure that it is processed correctly.

Reranker should be unique per project

---

Containerfile
ols/utils/ssl.py

We (Ansible Lightspeed) want to separate RAG content and embeddings images for building the service image.  Currently our RAG content image is about 3.1 GB, but the RAG content is only about 30 MB. 99% of the image was used for storing embeddings downloaded from HuggingFace. Since the embeddings used for chatbot are not updated frequently, including embeddings in the RAG content image is not efficient.
Note that both RAG content and embedding images point to the same image in this PR so that OLS build won't break, but it is possible to separate images by giving arguments in our downstream repo (ansible-chatbot-service).
- Closes #
- How were the fix/results from this change verified? Please …

Separate RAG content and embeddings images

---

.woke.yaml

Woke is getting triggered by existing contents of the repo. This prevents creation of any new commits, unless you disable the check entirely. 
- Closes #

woke linter made it impossible to commit any work

---

scripts/codecov.sh
scripts/transform_coverage_report.py

These scripts are required for successful compilation of coverage statistics.
Originally from https://github.com/road-core/service, they were missing in this repo.
- Closes #

Adding required scripts for coverage processing

---

README.md
docs/openapi.json
ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
ols/app/routers.py
ols/constants.py
ols/src/query_helpers/docs_summarizer.py
tests/e2e/test_streaming_query_endpoint.py
tests/integration/test_ols.py
tests/mock_classes/mock_llm_loader.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/endpoints/test_streaming_ols.py
tests/unit/app/models/test_models.py
tests/unit/query_helpers/test_docs_summarizer.py

OLS-39: Streaming endpoint

---

ols/app/models/config.py

Fixed type hints in `config` module

Fixed type hints in config module

---

ols/app/models/config.py

Bug fix: proper `OLSConfig` equality checks

Bug fix: proper OLSConfig equality checks

---

ols/src/prompts/prompt_generator.py
ols/src/query_helpers/docs_summarizer.py
ols/utils/token_handler.py
tests/unit/prompts/test_prompt_generator.py
tests/unit/query_helpers/test_docs_summarizer.py

In some situations, the OLS itself fails with an error of token limit exceeded (without even flowing to the LLM):
```
OLS controlled 413 http error: Prompt is too long
```
Although considering OLS token calculation may differ at some point from the LLM, this situation means some actual token calculations in the OLS code-base are prune to error.
So this is a fix for the OLS token calculation for available context (documents/history) length. 
- https://issues.redhat.com/browse/AAP-38368
In order to test it locally, I did:
1.- Set a small `context_window_size`, in order to quickly reproduce max_length issues, for example `2048`, and target `Granite 3.0` model provider
2.- Then just use an example prompt which causes relevant documents to exceed the available tokens, given expected response …

AAP-38368: Fixing sample prompt tokens calculations, which may cause further available token calculation issues

---

tests/unit/utils/test_config.py
tests/unit/utils/test_errors_parsing.py
tests/unit/utils/test_pyroscope.py
tests/unit/utils/test_redactor.py

Sync with downstream

---

ols/src/query_helpers/docs_summarizer.py
tests/unit/query_helpers/test_docs_summarizer.py

System Prompt Override added with #227 is no longer working.  System prompt was set using the
`_system_prompt` attribute of  `QueryHelper` class. However, the `DocsSummarizer` class, which extends
`QueryHelper`, now has `system_prompt` attribute, which does not contain the logic required for
System Prompt Override. We can simply use the `_system_prompt` attribute as it is set in the constructor
of `QueryHelper`.
- Closes #
Ansible Lightspeed chatbot has the UI to override system prompt and it can be used for verification.

Re-enable system prompt override

---

scripts/generate_openapi_schema.py

Verification if OpenAPI schema is up to date

Verification if OpenAPI schema is up to date

---

README.md

[doc] Auth user validation info

[doc] Auth user validation info

---

README.md

Fine tuning has a very specific meaning in area of machine learning. It involves modifications to select weights of a model. The subject described by section 11. is prompt engineering.
- Closes #

Rewritten section fine tuning to correctly reflect the subject

---

ols/app/models/config.py
ols/constants.py
ols/utils/checks.py
ols/utils/config.py
runner.py
tests/config/invalid_rhdh_config.yaml
tests/config/valid_rhdh_config.yaml
tests/config/valid_rhdh_config_multiple_providers.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_checks.py
tests/unit/utils/test_config.py

This PR adds the ability to load an additional configuration file alongside the `RCS_CONFIG_FILE`. This change currently supports the RHDH config map responsible for containing OLS plugin information, but can be extended to any additional configuration files. The file can be loaded and referenced similar to RCS through the `RHDH_CONFIG_FILE` environment variable.
The proposed change will grab all OLS related data and attempt to add providers defined in RHDH to RCS. These providers can then be used when hitting the `/query` endpoint.
You can find a demo overview of this change here: https://drive.google.com/file/d/1XDWqnSA7-Mz5hppiDAgDcIoYfNou3Tfn/view?usp=sharing
- Related Issue https://github.com/road-core/service/issues/335
- Closes https://github.com/road-core/service/issues/335
- JIRA …

Add Additional Config File Loading

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py

Similar code to OLS downstream
Minimize changes that are not compatible

Similar code to OLS downstream

---

docs/openapi.json
ols/app/endpoints/conversations.py
tests/integration/test_conversations.py

introduce `history_length` as an optional query param when retrieving chat history
historyLength will be a query param. which limits the APIs to only return latest #historyLength of comversations or last #historyLength messages in that conversation
- Related Issue https://issues.redhat.com/browse/RHDHPAI-522

add optional query param for history_length in GET & LIST conversations endpoint

---

ols/app/models/config.py
ols/user_data_collection/data_collector.py

Rather than storing some settings in harcoded constants, all is moved into configuration file, with the same defaults preserved.
I didn't get tests to work yet. As I'm getting errors due to way mocks are used in them.
```
TypeError: '<' not supported between instances of 'Mock' and 'int'
``` 
Simple mocks don't work, neither does the monkeypatch fixture.
- Closes #

Storing all user data collection parameters in config

---

CONTRIBUTING.md
Makefile

Tests are now executed with `pdm run` using the virtual environment installed.
This means that tests can be executed using `make` target invocation, without need for explicit activation of virtual environment. Pdm commands still work as they did before. 
Documentation has been amended to reflect the change and to refer to existing target.
- Run test targets using `make` in repo with installed virtual environment. Activation isn't necessary.

Simplifying test execution

---

ols/src/rag_index/index_loader.py

There was a bug in #412. Due to that bug, FAISS Vector DB is not loaded after #412 change.
- Closes # n/a

FAISS Vector DB is not loaded after pgvector support change

---

pdm.lock

Removed nvidia cu12 library

---

ols/src/query_helpers/topic_summarizer.py
tests/unit/query_helpers/test_topic_summarizer.py

We (Ansible Lightspeed Team) found that topic summarizer processing takes a long time when the Granite 3.1 model is used.  For example, just summarizing the one word query `Hello`, it takes 40 secs:
```
2025-03-05 14:46:32,133 [ols.src.query_helpers.topic_summarizer:topic_summarizer.py:83] DEBUG: 8ebe9851-dace-469c-86cd-c9e6f6da7249 summarizing user query: Hello
> Entering new LLMChain chain...
Prompt after formatting:
Instructions:
- You are a topic summarizer
- Your job is to extract precise topic summary from user input
For Input Analysis:
- Scan entire user message
- Identify core subject matter
- Distill essence into concise descriptor
- Prioritize key concepts
- Eliminate extraneous details
For Output Constraints:
- Maximum 5 words
- Uppercase first letter of significant words
- …
```

Skip Topic Summarizer when it is not needed

---

docs/openapi.json
ols/app/endpoints/conversations.py
ols/app/models/models.py
tests/integration/test_conversations.py

The current road-core list conversations API only returns `conversation_id` and `topic_summary` for each conversation.
this PR adds one more info, lastMessageTimestamp, to be returned. 
so that UI can group and list it.
for example:
- Related Issue https://issues.redhat.com/browse/RHDHPAI-650

include last_message_timestamp in list conversations API

---

README.md
docs/config.puml
examples/rcsconfig.yaml
ols/app/models/config.py

Make JSON events stream as default `application/json` format

Make JSON events stream as default `application/json` format

---

tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_quota_limiter_factory.py
tests/unit/quota/test_user_quota_limiter.py

Remove mock connect decorator from quota unit tests
Partially solves bug #427

Remove mock connect decorator from quota unit tests

---

.github/workflows/outdated_dependencies.yaml
.github/workflows/pydocstyle.yaml
.github/workflows/pylint.yaml

Fixes #389: Setting permissions in all GitHub actions
- Related Issue #389

Fixes #389: Setting permissions in all GitHub actions

---

tests/e2e/test_streaming_query_endpoint.py

OLS-1521: Switch to new granite-3-8b-instruct model from IBM
(this is the last remaining piece)
- Related Issue #OLS-1521

OLS-1521: Switch to new granite-3-8b-instruct model from IBM

---

docs/user_data_flow.uml
examples/rcsconfig.yaml
ols/app/models/config.py
ols/constants.py
ols/user_data_collection/README.md
ols/user_data_collection/data_collector.py
tests/config/valid_config.yaml
tests/unit/app/models/test_config.py
tests/unit/user_data_collection/test_data_collector.py
tests/unit/utils/test_config.py

Please don't merge this for now, until it's absolutely certain what will be necessary on the config side.
Included:
- script now reads config files only when called as main. 
- decorator turned into simple loop
- configuration for collector will now depend on collection being enabled
- there are no more default user agents
- tests of data collector no longer need global override for imports
- maximum size of user data is now defined in config
- `ingress_env` field of data collector configuration has been replaced with `ingress_url`
- user is now responsible for providing `ingress_url` if the collection is turned on
- Closes #
- How were the fix/results from this change verified? Please provide …

Refactoring the data collector script

---

tests/unit/llms/providers/test_azure_openai.py
tests/unit/llms/providers/test_watsonx.py
tests/unit/llms/test_llm_loader.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/query_helpers/test_question_validator.py
tests/unit/query_helpers/test_topic_summarizer.py
tests/unit/rag_index/test_index_loader.py
tests/unit/runners/test_quota_scheduler_runner.py
tests/unit/runners/test_uvicorn_runner.py
tests/unit/utils/test_config.py
tests/unit/utils/test_environments.py

Removed all remaining `@patch` decorators from unit tests
Fixes: #427

Removed all remaining @patch decorators from unit tests

---

ols/app/endpoints/health.py
ols/app/endpoints/ols.py
ols/src/llms/llm_loader.py
ols/src/llms/providers/provider.py
ols/src/query_helpers/docs_summarizer.py
ols/src/query_helpers/query_helper.py
ols/src/query_helpers/question_validator.py
ols/src/query_helpers/topic_summarizer.py
tests/unit/llms/providers/test_providers.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/query_helpers/test_query_helper.py
tests/unit/query_helpers/test_question_validator.py

Remove streaming parameter from providers
It is not needed, streaming can not be enabled for `/query` endpoint and is always enabled for `/streaming` one

Remove streaming parameter from providers

---

CONTRIBUTING.md
ols/src/llms/llm_loader.py

OLS-1615: Get rid of LLMChain in llm loader
- Related Issue #OLS-1615

OLS-1615: Get rid of LLMChain in llm loader

---

ols/customize/ols/prompts.py

before this change, with different models, the topic summary was returned inconsistent, some only Uppercase significant words, some will be all capitalized, e.g.
This PR updates the summarizer prompt to make the output more consistent, also gives examples on correct and incorrect output
- Related Issue https://issues.redhat.com/browse/RHDHPAI-723

enhance summarizer prompt to make it consistent

---

Makefile

Changing the default `make` target to be the `help`

Changing the default make target to be the help

---

ols/app/models/config.py
tests/config/valid_rhdh_config_multiple_providers.yaml
tests/unit/app/models/test_config.py

As part of the changes in https://github.com/road-core/service/pull/482 the ability to disable the model check was added. In order to incorporate that change with the parsing of Lightspeed configuration files I had to make a few tweaks.
This work is tracked in https://issues.redhat.com/browse/RHDHPAI-719
- Related Issue # https://issues.redhat.com/browse/RHDHPAI-719
- Closes # https://issues.redhat.com/browse/RHDHPAI-719
Updated the unit tests in place to reflect the new functionality, also ran through e2e on OpenShift to make sure it reads as expected.

Add Model Check Disabling Feature To RHDH Config Parsing

---

ols/src/query_helpers/question_validator.py

fix the model config is not defined bug in question validator when `disable_model_check: true` is set for a llm provider.
the `self.model_config` and `self.provider_config` should be referenced as it's been set in `__init__()`
- Closes #
To test the change, remove model list in a provider and set `disable_model_check: true` in rsconfig. 
also enable the question validator by setting `query_validation_method: llm`
test with and without the PR change

fix the model config is not defined bug in question validator

---

pdm.lock

OLS-1695: fixed 'h11 accepts some malformed Chunked-Encoding bodies'
- Related Issue #OLS-1695

OLS-1695: fixed 'h11 accepts some malformed Chunked-Encoding bodies'

---

tests/unit/rag_index/test_index_loader.py

Fixed OLS-1631: tests should not perform any API calls

Fixed OLS-1631: tests should not perform any API calls

---

examples/rcsconfig-local-ollama.yaml
examples/rcsconfig-pgvector.yaml
examples/rcsconfig.yaml

The query validation has been disabled by default in the code since the commit a7a0cc7706fb4d587eb4e4989630477d907c9a4b but, we left it enabled in the sample configuration files, which can cause some confusion for people that are experimenting with the project.
Not applicable
Not applicable, just sample configuration files to match the default configurations of the code.

Disable query_validation from sample configs

---

tests/unit/utils/test_config.py

Test that provider configurations are not `None`

Test that provider configurations are not None

---

ols/src/quota/cluster_quota_limiter.py
ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
ols/src/quota/token_usage_history.py
ols/src/quota/user_quota_limiter.py
tests/unit/cache/test_postgres_cache.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_token_usage_history.py
tests/unit/quota/test_user_quota_limiter.py

OLS-1714: reconnect Postgres quota DB when tables are deleted
- Related Issue #OLS-1714

OLS-1714: reconnect Postgres quota DB when tables are deleted

---

ols/app/models/config.py
tests/config/valid_rhdh_config.yaml
tests/config/valid_rhdh_config_multiple_providers.yaml
tests/unit/app/models/test_config.py

This change removes the `models` field from being recognized when parsing RHDH config. With how OLS works there will never be a `models` field in the yaml. Because of this, all providers parsed from OLS will have the model check disabled as the models are accessed via /models endpoint.
- Related Issue # N/A
- Closes # N/A

Remove models from lightspeed config in rhdh parsing

---

ols/src/cache/postgres_cache.py
tests/unit/cache/test_postgres_cache.py

This PR fixes a bug where an Excpetion was raised due to calling cursor.fetchone() after a DELETE SQL statement that did not return any results.
Now the DELETE statement was updated to include a RETURNING clause:
```sql
DELETE FROM cache 
WHERE user_id=%s AND conversation_id=%s
RETURNING conversation_id
```         
This ensures the query returns a result row if a conversation was deleted, making it safe to call `cursor.fetchone()`.
- Closes # https://github.com/road-core/service/issues/641
To test this change:
1. Use postgres type for conversation_cache.
```yaml
conversation_cache:
type: postgres
postgres:
host: localhost
port: 5432
dbname: postgres
user: postgres
password_path: postgres_password.txt
```
2. Create a conversation
3. Delete the newly created conversation using DELETE …

add RETURNING clause to delete conversation query in postgres_cache
