road-core/service

scripts/generate_packages_to_prefetch.py

Ability to filter packages
- Closes #

Ability to filter packages

---

README.md

Info about known issue in the tool
- Closes #

Info about known issue in the tool

---

ols/src/prompts/prompt_generator.py

(Trivial) more idiomatic if-else construct

(Trivial) more idiomatic if-else construct

---

.github/workflows/ruff.yaml

Ruff settings

---

.github/workflows/black.yaml

Configure Black on CI

---

ols/utils/auth_dependency.py

Better exception handling in auth module

Better exception handling in auth module

---

.github/workflows/radon.yaml

Radon on CI

---

.github/workflows/mypy.yaml

Mypy on CI

---

.github/workflows/unit_tests.yaml

Unit tests on CI

---

.github/workflows/integration_tests.yaml

Integration tests on CI

---

ols/app/models/config.py
ols/constants.py
ols/src/llms/providers/azure_openai.py
tests/config/valid_config_with_azure_openai_api_version.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

config: add api_version required for azure

config: add api_version required for azure

---

CONTRIBUTING.md

Updated contributing guide - reponame

Updated contributing guide - reponame

---

.github/workflows/integration_tests.yaml
.github/workflows/unit_tests.yaml

CI issue fix

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml
Makefile
ols/app/models/config.py
pdm.lock
pyproject.toml
scripts/evaluation/response_evaluation.py
scripts/evaluation/utils/constants.py
scripts/generate_packages_to_prefetch.py
tests/config/system_prompt.txt
tests/config/valid_config.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Sync with downstream 3

---

ols/src/query_helpers/docs_summarizer.py
ols/src/ui/gradio_ui.py
pdm.lock
pyproject.toml
tests/e2e/test_api.py
tests/e2e/utils/constants.py
tests/e2e/utils/ols_installer.py
tests/integration/test_authorized.py
tests/integration/test_feedback.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py
tests/integration/test_redis.py
tests/mock_classes/mock_llm_chain.py
tests/unit/query_helpers/test_docs_summarizer.py

Sync with downstream 4

---

.github/workflows/mypy.yaml
.github/workflows/pydocstyle.yaml
.github/workflows/pylint.yaml

Fix CI issues

---

Containerfile

Update Konflux references

---

README.md

Info about fine-tuned prompt in documentation

Info about fine-tuned prompt in documentation

---

pdm.lock
pyproject.toml

Fix DoS attack vector in Starlette package

Fix DoS attack vector in Starlette package

---

ols/app/endpoints/health.py
ols/app/main.py
ols/app/models/config.py
ols/src/llms/llm_loader.py
ols/src/prompts/prompts.py

Minor fixes in service source code

Minor fixes in service source code

---

ols/app/models/config.py
ols/utils/tls.py
tests/unit/app/models/test_config.py

TLS security profile in configuration

TLS security profile in configuration

---

Makefile
examples/olsconfig.yaml
ols/app/models/config.py
pyproject.toml
tests/config/config_for_integration_tests.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Sync with downstream changes

---

Makefile

- Related Issue #46
- Closes #

Update images target to generate requirements.txt

---

README.md

Change more references of OLS to RCS
Adjust the project name even further
- [ x] Documentation Update
- Closes #
- [ x] I have performed a self-review of my code.

Update README.md to reflect project name

---

scripts/evaluation/eval_data/question_answer_pair.json

Updated Q&A file

---

ols/constants.py
ols/src/llms/providers/provider.py
ols/utils/tls.py
runner.py
tests/unit/utils/test_tls.py

TLS security profile handlings

TLS security profile handlings

---

runner.py

Don't use f-strings in `runner.py`

Don't use f-strings in `runner.py`

---

README.md

Info about tls security provider in doc

Info about tls security provider in doc

---

runner.py

TLS security profile settings for the service

TLS security profile settings for the service

---

scripts/evaluation/utils/response.py

I've been working with @asamal4 to get the evaluation tooling running against a local ollama.  He suggested that I apply this change locally but I'm assuming we want this changed in the project as well.
- Closes #

Use provider config type rather than provider when loading vanilla model

---

tests/config/operator_install/olsconfig.crd.rhelai_vllm.yaml
tests/scripts/test-e2e-cluster.sh

OLS-987: Add RHELAI as a provider in prow CI

OLS-987: Add RHELAI as a provider in prow CI

---

scripts/evaluation/eval_data/question_answer_pair.json
scripts/evaluation/response_evaluation.py
scripts/evaluation/utils/constants.py
scripts/evaluation/utils/prompts.py
scripts/evaluation/utils/relevancy_score.py
scripts/evaluation/utils/response.py
scripts/evaluation/utils/score.py

Answer evalutation fixes

---

scripts/sync_repos.py

Explicit check parameter for `subprocess.run`

Explicit check parameter for `subprocess.run`

---

pdm.lock
pyproject.toml

Bump-up PDM tool to version 2.20.0.post1

Bump-up PDM tool to version 2.20.0.post1

---

examples/rcsconfig.yaml
ols/app/models/config.py
ols/constants.py
tests/unit/app/models/test_config.py

Auth module configuration

---

tests/config/minimal_config.yaml
tests/integration/random_payload_generator.py
tests/integration/test_config.py

Fuzzy tests for config loader

---

ols/src/auth/auth.py
runner.py
tests/unit/auth/test_auth.py
tests/unit/auth/test_k8s.py

K8s as configurable component

---

ols/app/endpoints/health.py

Simpler logic

---

pdm.lock
pyproject.toml

Bump-up Uvicorn to version 0.32.0

Bump-up Uvicorn to version 0.32.0

---

examples/rcsconfig.yaml

Use newer GPT model in example config

Use newer GPT model in example config

---

examples/rcsconfig.yaml

Updated configuration example file: info about validation methods

Updated configuration example file: info about validation methods

---

pdm.lock
pyproject.toml

Bump-up azure identity

---

ols/app/endpoints/authorized.py
ols/app/endpoints/feedback.py
ols/app/endpoints/ols.py
ols/app/metrics/metrics.py
ols/src/auth/auth.py
ols/src/auth/auth_dependency_interface.py
ols/src/auth/k8s.py
ols/src/auth/noop.py
tests/unit/app/endpoints/test_authorized.py

Fully configurable auth dependency

Fully configurable auth dependency

---

ols/src/auth/auth.py
ols/src/auth/auth_dependency_interface.py

Check that auth.config is provided

Check that auth.config is provided

---

ols/utils/tls.py

Logger in TLS module

---

tests/unit/auth/test_auth.py
tests/unit/auth/test_noop_auth_dependency.py

Added new unit tests

---

Containerfile

Update RAG reference

---

ols/utils/ssl.py
runner.py
tests/unit/utils/test_ssl.py

Refactor `runner.py` - SSL-related utility functions

Refactor runner.py - SSL-related utility functions

---

ols/src/query_helpers/docs_summarizer.py

Refactoring: deleted unused code

Refactoring: deleted unused code

---

pdm.lock
pyproject.toml

Bump-up scikit-learn to 1.5.2

---

pyproject.toml

PDM command to generate `requirements.txt` file

PDM command to generate requirements.txt

---

pdm.lock
pyproject.toml

OLS-1218: HTTPX client in `requirements.txt`

OLS-1218: HTTPX client in requirements.txt

---

tests/integration/test_authorized.py
tests/integration/test_metrics.py

Fixed integration tests

---

ols/utils/certificates.py
runner.py
tests/unit/extra_certs/test_extra_certs.py

Refactoring `runner.py` - certificates handling

Refactoring runner.py - certificates handling

---

ols/app/models/config.py
ols/runners/__init__.py
ols/runners/uvicorn.py
runner.py
tests/unit/runners/test_uvicorn_runner.py

OLS-1229: refactor Uvicorn runner into its own module + fix in configuration
- Closes #

OLS-1229: refactor Uvicorn runner into its own module + fix in configuration

---

ols/app/models/config.py
ols/runners/__init__.py
ols/runners/uvicorn.py
runner.py
tests/unit/runners/test_uvicorn_runner.py

OLS-1229: refactor Uvicorn runner into its own module
Added unit tests as required

OLS-1229: refactor Uvicorn runner into its own module

---

ols/app/metrics/__init__.py
pyproject.toml
tests/e2e/__init__.py

Fix Ruff issues

---

ols/utils/environments.py
runner.py
tests/unit/utils/test_environments.py

OLS-1229: HuggingFace environment settings

OLS-1229: HuggingFace environment settings

---

README.md

(doc) New PDM commands

---

ols/app/main.py
ols/src/cache/redis_cache.py
pdm.lock
pyproject.toml
tests/e2e/utils/cluster.py

Update Ruff to version 0.8.0

---

ols/src/query_helpers/docs_summarizer.py
ols/utils/token_handler.py

fix: end of token in granite-13b response

fix: end of token in granite-13b response

---

ols/app/main.py
tests/unit/app/models/test_config.py

Synced with downstream

---

tests/unit/extra_certs/__init__.py
tests/unit/runners/__init__.py
tests/unit/user_data_collection/__init__.py

Added missing `__init__.py` into all unit tests subdirectories

Added missing __init__.py into all unit tests subdirectories

---

pyproject.toml

Links in project file

---

pdm.lock
pyproject.toml

Bump-up Torch to version 2.5.1 from 2.4.1

Bump-up Torch to version 2.5.1 from 2.4.1

---

tests/config/config_for_integration_tests.yaml
tests/integration/test_runners.py

OLS-1233: Integration tests for runners

OLS-1233: Integration tests for runners

---

pdm.lock
pyproject.toml

Devel dependencies needed to build and upload the archive

Devel dependencies needed to build and upload the archive

---

OWNERS
docs/openapi.json
ols/app/main.py
pyproject.toml

Bump-up to version 0.2.1

---

scripts/generate_openapi_schema.py
tests/e2e/conftest.py
tests/e2e/test_api.py

Script to generate OpenAPI schema

Script to generate OpenAPI schema

---

ols/src/rag_index/index_loader.py

Added missing types
- Closes #

Added missing types

---

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
pdm.lock
pyproject.toml
tests/benchmarks/test_redactor.py
tests/unit/app/endpoints/test_feedback.py
tests/unit/extra_certs/test_extra_certs.py
tests/unit/llms/providers/test_azure_openai.py
tests/unit/llms/providers/test_fake_provider.py
tests/unit/llms/providers/test_rhelai_vllm.py
tests/unit/llms/providers/test_rhoai_vllm.py
tests/unit/query_helpers/test_attachment_appender.py

Sync with OLS downstream

---

tests/e2e/test_api.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_user_feedback.py
tests/integration/test_ols.py
tests/integration/test_redis.py
tests/unit/auth/test_k8s.py

Consistent Pytest marks

---

ols/app/models/models.py
ols/constants.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/models/test_config.py
tests/unit/app/models/test_models.py

Sync with OLS

---

OWNERS

Update OWNERS add yangcao77

---

ols/version.py
pdm.lock
pyproject.toml
tests/integration/test_project_version_consistency.py

Dynamic version support

---

0005-Version-in-one-place-in-sources.patch
ols/app/main.py
ols/version.py
tests/integration/test_project_version_consistency.py

Version in one place

---

scripts/generate_openapi_schema.py
scripts/rcsconfig.yaml

Fix bug #180 - ability to generate schema
Fixes: #180

Fix bug #180 - ability to generate schema

---

Makefile
README.md
pyproject.toml
runner.py

Ability to print current version to stdout

Ability to print current version to stdout

---

ols/app/endpoints/ols.py

Remove condition for query validation if it is a follow-up question

Remove condition for query validation if it is a follow-up question

---

ols/src/llms/llm_loader.py
tests/benchmarks/test_prompt_generator.py

Switch to GPT 4o mini

---

ols/src/llms/providers/fake_provider.py

Updated import from deprecated package

Updated import from deprecated package

---

pdm.lock
pyproject.toml

Pylint as devel dependency

---

ols/app/models/config.py
tests/unit/app/models/test_config.py

Getter for missing configuration attribute

Getter for missing configuration attribute

---

Makefile

Enable Pylint on CI

---

ols/app/models/config.py
ols/utils/checks.py
tests/integration/test_config.py
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Refactor checkers to allow more Pydantic approach later

Refactor checkers to allow more Pydantic approach later

---

scripts/generate_openapi_schema.py

Fixed imports in scripts

---

tests/e2e/test_api.py

Test should not return anything to make linter happy

Test should not return anything to make linter happy

---

tests/e2e/test_api.py
tests/e2e/utils/cluster.py
tests/e2e/utils/metrics.py
tests/e2e/utils/ols_installer.py

Waiting for pod in e2e tests

---

ols/src/rag_index/index_loader.py

Minor: override Pylint issue with global statement usage

Minor: override Pylint issue with global statement usage

---

pyproject.toml

OLS-1277: basic support for Python 3.12

OLS-1277: basic support for Python 3.12

---

runner.py

Print Python version on startup

Print Python version on startup

---

Makefile

Adding retry logic to dependencies installations in makefile

Adding retry logic to dependencies installations in makefile

---

tests/benchmarks/test_config_loader.py

Fixed config loader benchmark

---

tests/benchmarks/test_docs_summarizer.py

OLS-1298: fix DocsSummarizer benchmark
- Related Issue #OLS-1298

OLS-1298: fix DocsSummarizer benchmark

---

tests/benchmarks/test_prompt_generator.py

OLS-1298: fix prompt generator benchmark

OLS-1298: fix prompt generator benchmark

---

scripts/build-container.sh

Script to build container images

Script to build container images

---

build.args
pdm.lock
pyproject.toml

Update reference to RAG image

---

ols/app/endpoints/feedback.py
ols/app/main.py
ols/src/cache/postgres_cache.py
ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/registry.py
ols/src/query_helpers/docs_summarizer.py
ols/user_data_collection/data_collector.py

Better error message

---

ols/app/models/config.py
ols/constants.py
ols/src/llms/llm_loader.py
ols/user_data_collection/data_collector.py
runner.py
scripts/generate_openapi_schema.py
tests/e2e/utils/ols_installer.py
tests/integration/test_config.py
tests/scripts/must_gather.py
tests/unit/llms/test_llm_loader.py

Config file specified on one place + all neded syncs.

Config file specified on one place + all neded syncs.

---

ols/constants.py

Proper default config file name

Proper default config file name

---

ols/src/query_helpers/query_docs.py
ols/src/query_helpers/question_validator.py
ols/src/rag_index/index_loader.py
ols/src/ui/gradio_ui.py
ols/user_data_collection/data_collector.py
ols/utils/redactor.py
ols/utils/token_handler.py

OLS-1313: Remove f-strings from service code

OLS-1313: Remove f-strings from service code

---

README.md
docs/config.puml
examples/openshift-lightspeed-tls.yaml
examples/rcsconfig-local-ollama.yaml
examples/rcsconfig.yaml
ols/app/models/config.py
ols/utils/pyroscope.py
pdm.lock
pyproject.toml
runner.py
tests/benchmarks/test_config_loader.py
tests/config/config_for_integration_tests.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py
tests/unit/utils/test_pyroscope.py

Adding pyroscope and memray dependencies

Adding pyroscope and memray dependencies

---

pdm.lock
pyproject.toml

Bump-up Uvicorn to 0.32.0

---

pdm.lock
pyproject.toml
scripts/generate_openapi_schema.py

Fixes from downstream

---

.github/workflows/pylint.yaml
Makefile

Pylint settings for scripts

---

tests/e2e/utils/cluster.py
tests/scripts/test-e2e-cluster-periodics.sh

Better method to check containers ready
- Closes #

Better method to check containers ready

---

tests/e2e/test_api.py
tests/e2e/utils/cluster.py
tests/scripts/test-e2e-cluster.sh

Generated certs rotation

---

tests/integration/test_authorized.py
tests/integration/test_feedback.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py
tests/integration/test_project_version_consistency.py

Import warning fixes in all integration tests

Import warning fixes in all integration tests

---

tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/utils/cluster.py
tests/integration/test_config.py
tests/integration/test_openapi.py
tests/integration/test_project_version_consistency.py

Specify encoding in all file `open` operation in tests

Specify encoding in all file open operation in tests

---

ols/app/models/config.py
tests/unit/app/models/test_config.py

DevConfig `__eq__ ` special method

DevConfig `__eq__ ` special method

---

pdm.lock
pyproject.toml

Bump-up `cryptography` package to version 44.0.0

Bump-up cryptography package to version 44.0.0

---

tests/e2e/utils/cluster.py

Refactoring: f-strings are possible

Refactoring: f-strings are possible

---

tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/test_attachments.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_user_feedback.py

No global variables in e2e tests

No global variables in e2e tests

---

pdm.lock
pyproject.toml

Bump-up langchain to version 0.3.12

Bump-up langchain to version 0.3.12

---

Makefile

Enable Pylint for tests

---

tests/unit/app/models/test_config.py

Added missing unit test: TLS configuration without TLS key path attribute

Added missing unit test: TLS configuration without TLS key path attribute

---

build.args

Update lightspeed RAG content

---

pdm.lock
pyproject.toml

Bump-up urllib3 to 2.2.3

---

Containerfile
build.args

Update lightspeed rag content 

---

tests/unit/app/models/test_config.py

Unit tests: QueryFilter equality checks

Unit tests: QueryFilter equality checks

---

Containerfile

Updated RAG content

---

Containerfile.redis

OLS-1328: update Redis to fix CVE

OLS-1328: update Redis to fix CVE

---

CONTRIBUTING.md

Updated info about linters

---

README.md

OLS-1276: doc about system prompt override mechanism

OLS-1276: doc about system prompt override mechanism

---

tests/e2e/conftest.py

Assert attributes in `session.config`

Assert attributes in session.config

---

ols/app/metrics/token_counter.py
tests/unit/app/metrics/test_token_counter.py

OLS-1228: readable token counter textual representation
- Related Issue #OLS-1228

OLS-1228: readable token counter textual representation

---

pdm.lock

OLS-1331: sync PDM lockfile

---

README.md
runner.py

Ability to dump configuration

---

tests/unit/app/metrics/test_token_counter.py

OLS-1337: Fixed import for generic token counter
- Related Issue #OLS-1337

OLS-1337: Fixed import for generic token counter

---

.github/workflows/check_dependencies.yaml

OLS-1336: Action to check dependencies, including transitive ones
- Related Issue #OLS-1336

OLS-1336: Action to check dependencies

---

README.md

Info about Redoc page

---

.github/workflows/outdated_dependencies.yaml

List outdated dependencies for each PR

List outdated dependencies for each PR

---

README.md

Fix media_type in readme

---

ols/app/endpoints/ols.py

Fixed type hints in endpoint impementations

Fixed type hints in endpoint impementations

---

ols/src/auth/noop.py
tests/integration/test_authorized_noop.py
tests/unit/auth/test_noop_auth_dependency.py

Support for user ID in no-op auth module

Support for user ID in no-op auth module

---

ols/app/endpoints/ols.py
ols/app/metrics/token_counter.py
ols/app/models/models.py
ols/src/query_helpers/docs_summarizer.py
ols/src/query_helpers/question_validator.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/metrics/test_token_counter.py

OLS-1228: TokenCounter as separate dataclass
- Related Issue #OLS-1228

OLS-1228: TokenCounter as separate dataclass

---

README.md

Docs query mechanisms

---

tests/unit/app/models/test_config.py

OLS config: new unit tests

---

tests/e2e/pytest.ini
tests/e2e/test_api.py

Adding new tag for user data collection

Adding new tag for user data collection

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py

Constant query endpoints

---

README.md
docs/openapi.json
ols/app/endpoints/authorized.py
ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py

User ID as optional REST API parameter

User ID as optional REST API parameter

---

Makefile

Fixed UML diagrams command

---

ols/app/endpoints/feedback.py
ols/utils/tls.py
tests/e2e/test_api.py

Don't redeclare outer scope var by local one

Dont redeclare outer scope var by local one

---

scripts/questions_gen.py
tests/e2e/test_api.py

Questions generator script
Synced with downstream

Questions generator script

---

tests/e2e/test_api.py

Fixed Postgres connection fixture

Fixed Postgres connection fixture

---

tests/integration/test_conversations.py
tests/integration/test_project_version_consistency.py
tests/mock_classes/mock_llm_chain.py
tests/unit/utils/test_redactor.py

Fixed issues found by Ruff

---

README.md
examples/rcsconfig.yaml
ols/constants.py
tests/benchmarks/test_prompt_generator.py
tests/config/auth_config.yaml
tests/config/config_for_integration_tests.yaml
tests/config/config_for_integration_tests_8443.yaml
tests/config/minimal_config.yaml
tests/config/operator_install/olsconfig.crd.bam.yaml
tests/config/operator_install/olsconfig.crd.watsonx.yaml
tests/config/test_app_endpoints.yaml
tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/test_query_endpoint.py
tests/e2e/utils/metrics.py
tests/integration/test_ols.py
tests/scripts/test-e2e-cluster-periodics.sh
tests/scripts/test-e2e-cluster.sh
tests/unit/app/models/test_config.py
tests/unit/prompts/test_prompt_generator.py

Switch to Granite 3-8b
- [] New feature

Switch to Granite 3-8b

---

ols/constants.py
tests/benchmarks/test_prompt_generator.py
tests/integration/test_ols.py
tests/unit/app/models/test_config.py
tests/unit/prompts/test_prompt_generator.py

Remove exact model name reference

Remove exact model name reference

---

tests/e2e/conftest.py
tests/e2e/test_streaming_query_endpoint.py

Sync e2e tests with downstream

Sync e2e tests with downstream

---

scripts/transform_coverage_report.py

Type hints for transform coverage report script

Type hints for transform coverage report script

---

scripts/rcsconfig.yaml

Updated minimal service configuration

Updated minimal service configuration

---

tests/unit/utils/test_token_handler.py

Test formatted history from Granite

Test formatted history from Granite

---

tests/config/empty_openai_api_key.yaml

Config to use new GTP model

---

ols/app/endpoints/health.py
ols/src/llms/llm_loader.py
ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
tests/unit/llms/providers/test_providers.py

Pass streaming parameter to LLM provider

Pass streaming parameter to LLM provider 

---

ols/customize/__init__.py

Trivial: fixed typo

---

tests/config/operator_install/olsconfig.crd.azure_openai.yaml
tests/config/operator_install/olsconfig.crd.openai.yaml
tests/config/with_openai_api_key.yaml

Switch to GPT 4o-mini in config

Switch to GPT 4o-mini in config

---

.github/workflows/shellcheck.yaml
Makefile

Shell check on CI

---

scripts/codecov.sh
scripts/olsconfig.yaml

Disable shellcheck linter rules

Disable shellcheck linter rules

---

scripts/generate_openapi_schema.py

Bug fix: schema generator

---

pdm.lock
pyproject.toml

Bump-up Black to version 25.1.0

Bump-up Black to version 25.1.0

---

.github/workflows/black.yaml
.github/workflows/mypy.yaml

Black installation with proper version

Black installation with proper version

---

pyproject.toml

New commands to verify sources and packages

New commands to verify sources and packages

---

README.md

Updated list of PDM commands

---

docs/openapi.json

Reformatted `openapi.json` file

Reformatted `openapi.json` file

---

.github/workflows/integration_tests.yaml
.github/workflows/pydocstyle.yaml
.github/workflows/radon.yaml
.github/workflows/ruff.yaml
.github/workflows/unit_tests.yaml

Unified GitHub workflow declarations

Unified GitHub workflow declarations

---

tests/unit/test_version.py

Unit test if project version is specified

Unit test if project version is specified

---

tests/unit/ui/test_gradio_ui.py

Unit test for checking system prompt usage in GradIO

Unit test for checking system prompt usage in GradIO

---

tests/benchmarks/test_question_validator.py

Fixed issue #345
- Related Issue #345

Fixed issue #345

---

tests/benchmarks/test_token_handler.py

Fix for #347: Fixed token handler benchmark
- Related Issue #347

Fix for #347: Fixed token handler benchmark

---

tests/benchmarks/test_question_validator.py
tests/mock_classes/mock_llm_loader.py

Fix #347: Benchmark for QuestionValidator
- Related Issue #347

Fix #347: Benchmark for QuestionValidator

---

docs/404.html
docs/Gemfile
docs/_config.yml
docs/index.md

Stub for GitHub pages

---

docs/_config.yml

Fixed GitHub pages style

---

docs/service_configuration_classes.md

[doc] Class hierarchy

---

docs/index.md

Updated index page

---

ols/app/models/models.py

Lightspeed core architecture
Partially fixes #361 
- Related Issue #361

Fixed types in models

---

ols/utils/token_handler.py

Fixed types in token handler
Fixes #361
- Related Issue #361

Fixed types in token handler

---

ols/app/endpoints/ols.py

Better logging user ID and conversation ID

Better logging user ID and conversation ID

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

Bump-up to version 0.3.0

---

tests/config/valid_rhdh_config.yaml
tests/unit/utils/test_config.py

Unit tests: loading additional RDHD configuration

Unit tests: loading additional RDHD configuration

---

pdm.lock
pyproject.toml

Bump-up Ruff to version 0.9.0

---

tests/config/valid_rhdh_config.yaml
tests/config/valid_rhdh_config_multiple_providers.yaml
tests/unit/app/models/test_config.py

Replaced insensitive words

---

tests/integration/test_ols.py
tests/integration/test_project_version_consistency.py

Sync with downstream

---

tests/unit/app/test_routers.py
tests/unit/llms/providers/test_providers.py
tests/unit/utils/test_config.py

Updated unit tests

---

.github/workflows/integration_tests.yaml

Integration tests matrix

---

pdm.lock
pyproject.toml

Security fix: cryptography module > 4.0.0

Security fix: cryptography module > 4.0.0

---

docs/openapi.json

Reformatted OpenAPI schema

---

Containerfile

Files are copied to container before they are used.
- Closes #383 
- N/A

Copying source before attempting to install it.

---

tests/config/config_for_integration_tests.yaml
tests/config/config_for_integration_tests_8443.yaml

Expanded configurations for integration tests
Forces all LLM options to be processed during configuration loading

Expanded configurations for integration tests

---

ols/src/quota/__init__.py
ols/src/quota/quota_exceed_error.py
ols/src/quota/quota_limiter.py
ols/src/quota/user_quota_limiter.py
tests/unit/quota/__init__.py
tests/unit/quota/test_user_quota_limiter.py

#44: User quota system

---

tests/e2e/test_streaming_query_endpoint.py

Enforce HTTP v1.0 to reduce end to end tests flakiness

Enforce HTTP v1.0 to reduce end to end tests flakiness

---

.github/workflows/shellcheck.yaml

Specify permissions for shellcheck GH action
- Related Issue #389

Specify permissions for shellcheck GH action

---

.github/workflows/unit_tests.yaml

Specify permissions for unit tests GH action
- Related Issue #389

Specify permissions for unit tests GH action

---

ols/src/quota/user_quota_limiter.py
tests/unit/quota/test_user_quota_limiter.py

Timestamps in user quota limiter table

Timestamps in user quota limiter table

---

ols/src/quota/quota_limiter.py
ols/src/quota/user_quota_limiter.py
tests/unit/quota/test_user_quota_limiter.py

Revoke quota ability

---

.github/workflows/integration_tests.yaml
.github/workflows/unit_tests.yaml

Run tests against Python 3.13 on CI
- Related Issue #OLS-1424

Run tests against Python 3.13 on CI

---

ols/src/quota/quota_limiter.py
ols/src/quota/user_quota_limiter.py
tests/unit/quota/test_user_quota_limiter.py

Ability to increase quota for user

Ability to increase quota for user

---

ols/src/quota/quota_limiter.py
ols/src/quota/user_quota_limiter.py

Refactoring: connection to DB

---

tests/e2e/utils/ols_installer.py

Adding logging to the olsconfig creation failure

Adding logging to the olsconfig creation failure

---

tests/unit/app/models/test_models.py

Unit tests for message encoders and decoders

Unit tests for message encoders and decoders

---

tests/unit/app/models/test_models.py

Cache entry encoding and decoding unit tests

Cache entry encoding and decoding unit tests

---

ols/app/models/models.py

Bug fix: Explicitly set message data type

Bug fix: Explicitly set message data type

---

ols/src/quota/user_quota_limiter.py
tests/unit/quota/test_user_quota_limiter.py

Consume tokens in transaction

---

.github/workflows/radon.yaml
.github/workflows/ruff.yaml

Setting GH action permissions
- Related Issue #389

Setting GH action permissions

---

scripts/evaluation/response_evaluation.py
scripts/evaluation/utils/prompts.py
scripts/evaluation/utils/relevancy_score.py
scripts/evaluation/utils/similarity_score_llm.py

eval: fix prompt & save temp score

eval: fix prompt & save temp score

---

ols/src/quota/user_quota_limiter.py
tests/unit/quota/test_user_quota_limiter.py

Unified quota limits table

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
tests/integration/test_ols.py
tests/unit/app/endpoints/test_ols.py

Fix: proper output from retrieve_previous_input
- Closes #

Refactoring query processor handling code

---

tests/unit/app/models/test_config.py

Added missing unit tests for reference content configuration

Added missing unit tests for reference content configuration

---

ols/src/quota/cluster_quota_limiter.py
ols/src/quota/quota_exceed_error.py
ols/src/quota/revokable_quota_limiter.py
ols/src/quota/user_quota_limiter.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_quota_exceed_error.py
tests/unit/quota/test_user_quota_limiter.py

Cluster quota limiter

---

ols/src/quota/quota_exceed_error.py
tests/unit/quota/test_quota_exceed_error.py

Better quota exceed error type

Better quota exceed error type

---

ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_user_quota_limiter.py

Ensure available quota

---

ols/app/models/config.py

Added missing eq comparator

---

examples/rcsconfig-pgvector.yaml
ols/app/models/config.py
ols/constants.py
ols/src/rag_index/index_loader.py
pdm.lock
pyproject.toml
tests/unit/app/models/test_config.py
tests/unit/rag_index/test_index_loader.py

For https://github.com/road-core/service/issues/173.
Add Postgres (pgvector) support to road-core/service. 
Changes in road-core/rag-content is found in https://github.com/road-core/rag-content/pull/26
https://github.com/user-attachments/assets/5d8d120b-50cc-4390-88c5-e35da9bed6b9
- Related Issue # [AAP-39758](https://issues.redhat.com/browse/AAP-39758)
- Closes # n/a

pgvector support

---

ols/constants.py
ols/src/quota/quota_limiter_factory.py
tests/unit/quota/test_quota_limiter_factory.py

Quota limiter factory 

---

ols/utils/config.py
tests/unit/utils/test_config.py

Quota limiters config property

Quota limiters config property

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py

Refactoring: token counter helpers

Refactoring: token counter helpers

---

tests/e2e/conftest.py
tests/e2e/pytest.ini
tests/e2e/test_api.py
tests/e2e/test_streaming_query_endpoint.py

Synced e2e tests with downstream

Synced e2e tests with downstream

---

pdm.lock
pyproject.toml

Fix CVE in jinja2 package

---

ols/src/quota/quota_limiter.py

Type fix in abstract methods

---

examples/minimal_rcsconfig.yaml

Minimal RCS configuration

---

ols/app/endpoints/ols.py
tests/unit/app/endpoints/test_ols.py

Consuming tokens logic

---

ols/runners/uvicorn.py

Logging in Uvicorn runner

---

ols/app/models/config.py
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Changed quota scheduler attribute

Changed quota scheduler attribute

---

tests/e2e/utils/ols_installer.py

Adding option to install bundle via provided image

Adding option to install bundle via provided image

---

ols/app/endpoints/streaming_ols.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/endpoints/test_streaming_ols.py

Synced OLS endpoints tests

---

ols/runners/quota_scheduler.py
runner.py
tests/config/config_for_integration_tests_quota_limiters.yaml
tests/integration/test_runners.py
tests/unit/runners/test_quota_scheduler_runner.py

Quota scheduler for the service

Quota scheduler for the service

---

ols/app/models/config.py
ols/runners/quota_scheduler.py
ols/src/quota/quota_limiter_factory.py
ols/utils/config.py
tests/config/config_for_integration_tests_quota_limiters.yaml
tests/unit/app/models/test_config.py
tests/unit/quota/test_quota_limiter_factory.py
tests/unit/runners/test_quota_scheduler_runner.py
tests/unit/utils/test_config.py

OLS-1486: quota limiters to quota handlers
- Related Issue #OLS-1486

OLS-1486: quota limiters to quota handlers

---

ols/app/endpoints/streaming_ols.py

Consume tokens for streaming endpoint

Consume tokens for streaming endpoint

---

docs/LnL.md

Add MacOS instructions to LnL toc

Add instructions for MacOS instructions to LnL ToC

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/config.py
ols/src/quota/token_usage_history.py
ols/utils/config.py
tests/unit/app/endpoints/test_ols.py
tests/unit/quota/test_token_usage_history.py

Token history usage

---

.coveragerc

Do not measure coverage for type checks imports

Do not measure coverage for type checks imports

---

ols/src/llms/providers/watsonx.py
tests/mock_classes/mock_watsonxllm.py
tests/unit/llms/providers/test_watsonx.py

Migrate to WatsonAI

---

tests/unit/prompts/test_prompt_generator.py

Refactored prompt generator unit test

Refactored prompt generator unit test

---

ols/constants.py
scripts/evaluation/utils/models.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py
tests/unit/app/models/test_config.py

Increase default context window size

Increase default context window size

---

docs/openapi.json
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/models/test_models.py

Unified referenced documents in query endpoints
Fixes #334
- Related Issue #334

Unified referenced documents in query endpoints

---

docs/openapi.json
ols/app/models/models.py
ols/utils/token_handler.py
scripts/evaluation/query_rag.py
tests/e2e/test_query_endpoint.py
tests/mock_classes/mock_query_engine.py
tests/mock_classes/mock_retrievers.py
tests/unit/utils/test_token_handler.py

Unified referenced documents in query endpoints - leftovers

Unified referenced documents in query endpoints - leftovers

---

ols/utils/token_handler.py
tests/mock_classes/mock_retrievers.py
tests/unit/utils/test_token_handler.py

Fixes in referenced docs

---

tests/e2e/test_query_endpoint.py

Minor fix in e2e tests

---

tests/integration/test_authorized.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py
tests/integration/test_runners.py

Patch for dictionary with environment variables

Patch for dictionary with environment variables

---

tests/unit/app/endpoints/test_authorized.py
tests/unit/app/endpoints/test_feedback.py
tests/unit/app/endpoints/test_health.py
tests/unit/app/endpoints/test_ols.py

OLS-1519 no `patch` in app unit tests
- Related Issue #OLS-1519

OLS-1519 no `patch` in app unit tests

---

tests/unit/auth/test_k8s.py
tests/unit/auth/test_noop_auth_dependency.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_token_usage_history.py
tests/unit/quota/test_user_quota_limiter.py

OLS-1519: no `patch` in auth and quota unit tests
- Related Issue #OLS-1519

OLS-1519: no patch auth quota unit tests

---

tests/mock_classes/mock_llama_index.py
tests/mock_classes/mock_llm_chain.py
tests/mock_classes/mock_redis_client.py

Info about `@patch` decorator in all mock classes where applicable

Info about @patch decorator in all mock classes where applicable

---

CONTRIBUTING.md

Modifying section on patching to discourage use of decorators

---

ols/app/main.py
tests/integration/test_metrics.py

Metrics endpoint fix

---

tests/unit/app/endpoints/test_ols.py

Missing unit tests for quota limiters

Missing unit tests for quota limiters

---

scripts/sync_repos.py

Script to sync repositories

---

ols/app/endpoints/conversations.py

Fixed module docstring - conversation history

OLS-1615: Fixed module docstring - conversation history

---

ols/app/metrics/token_counter.py

Remove llm chain from token counter
- Related Issue #OLS-1615

OLS-1615: Remove llm chain from token counter

---

ols/src/query_helpers/question_validator.py
tests/integration/test_ols.py
tests/mock_classes/_mock_llm_chain.py
tests/mock_classes/mock_llm_loader.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/query_helpers/test_question_validator.py

OLS-1615: No LLM chain in QuestionValidator
- Related Issue #OLS-1615

OLS-1615: No LLM chain in QuestionValidator

---

ols/src/cache/cache_factory.py
ols/src/cache/postgres_cache.py
tests/unit/cache/test_postgres_cache.py

OLS-1627: Fix PG issue
- Related Issue #OLS-1627

OLS-1627: Fix PG issue

---

ols/src/query_helpers/docs_summarizer.py
ols/utils/token_handler.py

Remove handling of endtoken tokens

Remove handling of endtoken tokens

---

ols/customize/ols/__init__.py

[minor] Fix typo

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

Bump-up version to 0.3.1

---

ols/app/models/config.py
ols/src/llms/providers/fake_provider.py
ols/src/llms/providers/provider.py
tests/unit/llms/providers/test_fake_provider.py

Add FakeStreamingListLLM to fake_provider for streaming test
With this llm_provider definition:
```
llm_providers:
- name: fake
type: fake_provider
models:
- name: fake_model
fake_provider_config:
url: http://example.com/
stream: true
response: Hello
chunks: 60
sleep: 0.1
```
following streaming outputs are generated:
https://github.com/user-attachments/assets/88d176a8-94c9-4189-b3a4-14d30275b12c
- **url**  _str_ (ignored)
- **stream** _bool_ Whether streaming is enabled or not. Deafult is false.
- **response** _str_ The string that is used in the streaming or non-streaming output. Default is `This is a preconfigured fake response.`. 
- **chunks** _int_ The number of chunks to be generated in the streaming response. Each chunk contains one character of stream data. If the length of …

Support FakeStreamingListLLM

---

tests/mock_classes/mock_tools.py

Mock class for testing tools

---

ols/src/llms/providers/azure_openai.py
tests/unit/llms/providers/test_azure_openai.py

Fix cache value for Azure OpenAI expiration

Fix cache value for Azure OpenAI expiration

---

tests/e2e/utils/ols_installer.py

Updated OLS installer for e2e tests

Updated OLS installer for e2e tests

---

tests/e2e/conftest.py
tests/e2e/test_api.py

Updated conftest for end to end tests

Updated conftest for end to end tests

---

ols/app/main.py
ols/customize/__init__.py
ols/customize/ols/metadata.py
tests/config/operator_install/olsconfig.crd.azure_openai_introspection.yaml
tests/config/operator_install/olsconfig.crd.openai_introspection.yaml
tests/config/operator_install/olsconfig.crd.watsonx_introspection.yaml
tests/integration/test_openapi.py

Service name fully customizable

Service name fully customizable

---

ols/app/models/config.py
ols/utils/config.py
tests/config/config_for_integration_tests.yaml
tests/config/valid_config.yaml
tests/integration/test_ols.py
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

LCORE-22: MCP servers configuration
- Related Issue #LCORE-22

LCORE-22: MCP servers configuration

---

pdm.lock

Bump-up dependencies

---

ols/app/models/config.py
ols/constants.py
ols/customize/ols/prompts.py
tests/config/config_for_integration_tests.yaml
tests/config/valid_config.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Model for MCP server transport configuration options
- Related Issue #LCORE-22

Model for MCP server transport configuration options

---

.github/workflows/bandit.yaml

Enable bandit on CI
- Related Issue #LCORE-54
- Closes #

Enable bandit on CI

---

README.md

Updated docs: quota limits

---

docs/openapi.json
pdm.lock
pyproject.toml

Dependency updates

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py

In OCP docs version test, check the URL

In OCP docs version test, check the URL

---

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
tests/unit/llms/providers/test_openai.py
tests/unit/llms/providers/test_providers.py
tests/unit/llms/providers/test_rhelai_vllm.py
tests/unit/llms/providers/test_rhoai_vllm.py

Add `async_client` for async LLM requests

Add `async_client` for async LLM requests

---

tests/scripts/must_gather.py

Updated must-gather script

---

tests/e2e/utils/cluster.py
tests/e2e/utils/retry.py

Ability to debug e2e service startup issues

Ability to debug e2e service startup issues

---

tests/e2e/utils/cluster.py
tests/e2e/utils/ols_installer.py

More debug messages in end to end tests
- [*] End to end tests

More debug messages in end to end tests

---

ols/app/models/config.py

LCORE-71: fixed config names
- Related Issue #LCORE-71

LCORE-71: fixed config names

---

README.md

Fixed quota limits doc

---

tests/e2e/pytest.ini
tests/e2e/test_api.py
tests/e2e/utils/ols_installer.py

Updates in e2e tests

---

ols/constants.py
runner.py

LCORE-72: better config dump
- Related Issue #LCORE-72

LCORE-72: better config dump

---

.github/workflows/shellcheck.yaml

LCORE-78: fix CI jobs settings
- Related Issue #LCORE-78

LCORE-78: fix CI jobs settings

---

scripts/rcsconfig.yaml

Proper service config for `make schema` target

Proper service config for make schema target

---

ols/constants.py
ols/src/auth/auth.py
ols/src/auth/noop_with_token.py
tests/unit/auth/test_auth.py
tests/unit/auth/test_noop_with_token.py

Noop with token auth module

---

tests/constants.py

Change OCP docs version for tests

Change OCP docs version for tests

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py
tests/e2e/utils/decorators.py

Increasing retry time in e2e tests

Increasing retry time in e2e tests

---

ols/src/cache/postgres_cache.py
tests/unit/cache/test_postgres_cache.py

OLS-1654: refactor connection to Postgres DB

OLS-1654: refactor connection to Postgres DB

---

ols/src/cache/postgres_cache.py

OLS-1654: Refactored connect to PG

OLS-1654: Refactored connect to PG

---

tests/e2e/evaluation/__init__.py
tests/e2e/evaluation/test_evaluation.py

Evaluation tests

---

ols/utils/connection_decorator.py
tests/unit/utils/test_connection_decorator.py

OLS-1654: connection decorator

OLS-1654: connection decorator

---

ols/src/cache/postgres_cache.py
ols/src/quota/quota_limiter.py
tests/unit/cache/test_postgres_cache.py

OLS-1654: connection decorator in PG cache

OLS-1654: connection decorator in PG cache

---

scripts/evaluation/eval_data/question_answer_pair.json

Updated score for QA pairs

---

ols/app/models/config.py
tests/config/config_for_integration_tests.yaml
tests/config/valid_config.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Refactor MCP server config

---

tests/unit/cache/test_postgres_cache.py

OLS-1654: tests if DB operations performs recconnection

OLS-1654: tests if DB operations performs reconnection

---

ols/app/endpoints/ols.py

Better error message for disconnected PG

Better error message for disconnected PG

---

ols/src/quota/quota_limiter.py

Logger in quota limiter

---

README.md

Doc for quota limiters

---

ols/src/cache/postgres_cache.py
ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
ols/src/quota/token_usage_history.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_token_usage_history.py
tests/unit/quota/test_user_quota_limiter.py

OLS-1654 final updates

---

pdm.lock

Bump-up deps

---

tests/e2e/test_streaming_query_endpoint.py
tests/e2e/utils/ols_installer.py

Changing timeout for streaming tests

Changing timeout for streaming tests

---

pdm.lock
pyproject.toml

LCORE-83: bump-up PyTorch to 2.7.0
- Related Issue #LCORE-83

LCORE-83: bump-up PyTorch to 2.7.0

---

pdm.lock

Regenerated lockfile

---

tests/e2e/test_query_endpoint.py

fix: e2e number chunks retrieved check

fix: e2e number chunks retrieved check

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py

e2e: add streaming rag for introspection

e2e: add streaming rag for introspection

---

pyproject.toml

`Ragas` as optional dependency

Ragas as optional dependency

---

ols/app/models/models.py
ols/src/prompts/prompt_generator.py
ols/src/quota/quota_exceed_error.py

Added missing type annotation

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

Bump-up to version 0.3.2

---

docs/road_core_as_dependency.md

Road core as dependency doc

---

.github/workflows/pyright.yaml

Enable Pyright on CI

---

ols/app/metrics/metrics.py

Use `Annotated` in feedback endpoint handler

Use Annotated in feedback endpoint handler

---

ols/runners/uvicorn.py

Proper `AppConfig` parameter type to start Uvicorn

Proper AppConfig parameter type to start Uvicorn

---

ols/src/auth/auth.py
tests/unit/auth/test_auth.py

Removed unreachable code

---

ols/runners/quota_scheduler.py

Proper `AppConfig` parameter type to start quota runner

Proper AppConfig parameter type to start quota runner

---

Makefile

Makefile target to generate `config.uml`

Makefile target to generate config.uml

---

Makefile

Makefile target to perform test evaluation

Makefile target to perform test evaluation

---

ols/customize/rhdh/__init__.py
ols/customize/rhdh/keywords.py
ols/customize/rhdh/metadata.py
ols/customize/rhdh/prompts.py
ols/customize/rhdh/reranker.py

This PR creates rhdh customized prompt folder
https://issues.redhat.com/browse/RHDHPAI-747
https://issues.redhat.com/browse/RHDHPAI-748
https://issues.redhat.com/browse/RHDHPAI-749

rhdh customized prompt 

---

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
ols/src/llms/providers/watsonx.py
tests/unit/llms/providers/test_providers.py
tests/unit/llms/test_llm_loader.py

Proper types for LLM providers chat objects

Proper types for LLM providers chat objects

---

tests/unit/llms/providers/test_azure_openai.py

Proper types for Azure config tests

Proper types for Azure config tests

---

ols/app/main.py

Fixed streaming response type

---

ols/utils/certificates.py

Added missing warning when no certificate directory is specified

Added missing warning when no certificate directory is specified

---

docs/openapi.json
ols/app/endpoints/health.py

Proper description for liveness REST API endpoint

Proper description for liveness REST API endpoint

---

scripts/evaluation/utils/constants.py
scripts/evaluation/utils/plot.py
scripts/evaluation/utils/prompts.py
scripts/evaluation/utils/rag.py
scripts/evaluation/utils/response.py

Sync utils

---

tests/benchmarks/test_errors_parsing.py
tests/unit/utils/test_errors_parsing.py

Use proper `Response` objects in tests

Use proper Response objects in tests 

---

ols/plugins/__init__.py
tests/integration/test_authorized.py
tests/integration/test_metrics.py
tests/mock_classes/mock_retrievers.py
tests/unit/extra_certs/test_extra_certs.py

Minor fixes  

---

tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/test_attachments.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py
tests/e2e/test_user_feedback.py
tests/e2e/xxx

Handling custom `pytest` attributes by linters

Handling custom pytest attributes by linters

---

docs/openapi.json
examples/openshift-lightspeed-tls.yaml
examples/rcsconfig.yaml
ols/app/models/models.py
ols/src/llms/llm_loader.py
scripts/rcsconfig.yaml
tests/config/auth_config.yaml
tests/config/config_for_integration_tests.yaml
tests/config/config_for_integration_tests_8443.yaml
tests/config/config_for_integration_tests_quota_limiters.yaml
tests/config/empty_openai_api_key.yaml
tests/config/minimal_config.yaml
tests/config/test_app_endpoints.yaml
tests/config/with_openai_api_key.yaml
tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py
tests/e2e/utils/metrics.py
tests/integration/test_ols.py
tests/unit/app/models/test_models.py

Remove unnecessary reference to exact model name

Remove unnecessary reference to exact model name

---

docs/openapi.json
ols/version.py

Bump-up version to 0.3.3

---

docs/LnL.md
docs/index.md
docs/presentation.md
docs/road_core_as_dependency.md
docs/service_configuration_classes.md

GitHub pages updates

---

docs/LnL.md
docs/_config.yml
docs/index.md
docs/presentation.md
docs/road_core_as_dependency.md
docs/service_configuration_classes.md

Fix GitHub pages

---

README.md
docs/installation_linux.md
docs/installation_macos.md

Refactored README: installation steps

Refactored README: installation steps

---

tests/e2e/evaluation/test_evaluation.py

Minor fixes in evaluation tests

Minor fixes in evaluation tests

---

README.md

Fixed links to installation procedures

Fixed links to installation procedures

---

tests/e2e/utils/cluster.py

Fix: wait_for_running_pod always check the running pods

Fix: wait_for_running_pod always check the running pods

---

tests/e2e/utils/ols_installer.py

Minor fixes in OLS installer

---

tests/mock_classes/mock_retrieved_node.py

Fixed mock retrieved node class

Fixed mock retrieved node class

---

tests/integration/test_ols.py

Ensure response is not None

---

pdm.lock

Update lockfile to latest version

Update lockfile to latest version

---

pdm.lock
pyproject.toml

Bump-up `langchain-ibm`

---

tests/unit/app/endpoints/test_ols.py

Added checks for conversation ID value

Added checks for conversation ID value

---

docs/openapi.json
ols/version.py

Bump-up version to 0.3.4

---

tests/scripts/test-e2e-cluster-periodics.sh
tests/scripts/test-e2e-cluster.sh
tests/scripts/test-evaluation.sh
tests/scripts/utils.sh

Updated all e2e scripts

---

.woke.yaml

Updated woke config file

---

ols/constants.py

Tool call constants

---

README.md

Update badge source based repo

Update License badge source

---

pdm.lock

Bump-up Ruff

---

ols/app/endpoints/ols.py

Fix provider-model checks

---

ols/utils/ssl.py

Fix function return type
